Tabbed Shelf Icon
gnustep/apps-gworkspace pull request #16
Opened 2021-11-12 11:11 UTC by rmottola

* Make  TShelfPBIcon inherit from a common superclass TShelfIcon
* Derive TShelfFileIcon from common superclasss TShelfIcon
* fix crashers with drag&drop
* some cleanup and cruft remove

2021-11-12 22:34 UTC, fredkiefer requested changes

2021-11-12 22:34 UTC, fredkiefer commented on GWorkspace/TShelf/TShelfFileIcon.m
> +	ASSIGN (icon, [fsnodeRep iconOfSize: ICON_SIZE forNode: node]);
Please add indentation and braces.

2021-11-12 22:34 UTC, fredkiefer commented on GWorkspace/TShelf/TShelfFileIcon.m
> +	hlightRect.size.height = ICON_SIZE + 4;
Same here

2021-11-12 22:34 UTC, fredkiefer commented on GWorkspace/TShelf/TShelfFileIcon.m
> +  RELEASE (node);
This will lead to a double free as you already release node below.

2021-11-12 22:34 UTC, fredkiefer commented on GWorkspace/TShelf/TShelfFileIcon.m
> +	      [[self window] postEvent: nextEvent atStart: NO];
If you post the event at the end of the queue, events might be in the wrong order now.

2021-11-12 22:34 UTC, fredkiefer commented on GWorkspace/TShelf/TShelfFileIcon.m
> +- (void)startExternalDragOnEvent:(NSEvent *)event
This method seems to be useless. Just rely on super class.

2021-11-12 22:34 UTC, fredkiefer commented on GWorkspace/TShelf/TShelfFileIcon.m
> +  if ([pb setPropertyList: paths forType: NSFilenamesPboardType] == NO)
Having just the statement without the "if" would have the same effect.

2021-11-12 22:34 UTC, fredkiefer commented on GWorkspace/TShelf/TShelfFileIcon.m
> +- (void)draggedImage:(NSImage *)anImage
Again this method is not needed.

2021-11-12 22:34 UTC, fredkiefer commented on GWorkspace/TShelf/TShelfIconsView.m
>  - (NSComparisonResult)pbiconCompare:(id)other
Why is there a different method with the same code as above?

2021-11-12 22:34 UTC, fredkiefer commented on GWorkspace/TShelf/TShelfPBIcon.m
>  - (void)drawRect:(NSRect)rect
Again an unneeded method

2021-11-12 22:34 UTC, fredkiefer commented on GWorkspace/TShelf/TShelfPBIcon.m
> +  [super startExternalDragOnEvent:event withMouseOffset:offset];
One more

2021-11-12 22:34 UTC, fredkiefer commented on GWorkspace/TShelf/TShelfPBIcon.m
> +  [super draggedImage:anImage endedAt:aPoint deposited:flag];
Another one

2021-11-12 22:34 UTC, fredkiefer commented on GWorkspace/TShelf/TShelfFileIcon.m
> +      namelabel = [NSTextField new];
To me it is not clear why this instance is defined on the super class but only ever set in this subclass. This looks wrong and would result in more methods being moved down to the subclass.

2021-11-13 21:42 UTC, rmottola commented on GWorkspace/TShelf/TShelfFileIcon.m
> +	ASSIGN (icon, [fsnodeRep iconOfSize: ICON_SIZE forNode: node]);
Do we have a code-style mandating brackets for single statements? I don't like that personally.
Indentation looks bad though, the code is original GWorkspace code though, I'll reformatted only  the one I touched/changed.

2021-11-13 21:48 UTC, rmottola commented on GWorkspace/TShelf/TShelfFileIcon.m
> +  RELEASE (node);
you mean paths? indeed, I removed the second destroy and substituted it with a simple assignment to nil.

2021-11-13 21:51 UTC, rmottola commented on GWorkspace/TShelf/TShelfFileIcon.m
> +	      [[self window] postEvent: nextEvent atStart: NO];
How can I repost it then? without there were malfunctions, I found that in other icons of the Dock too.

2021-11-13 21:53 UTC, rmottola commented on GWorkspace/TShelf/TShelfFileIcon.m
> +- (void)startExternalDragOnEvent:(NSEvent *)event
Ok, I thought it would be cleaner to instantiate all methods and in case no custom was needed, super it.

2021-11-13 22:04 UTC, rmottola commented on GWorkspace/TShelf/TShelfPBIcon.m
> +  [super startExternalDragOnEvent:event withMouseOffset:offset];
Ok, removed.

2021-11-13 22:04 UTC, rmottola commented on GWorkspace/TShelf/TShelfPBIcon.m
> +  [super draggedImage:anImage endedAt:aPoint deposited:flag];
Ok

2021-11-13 22:55 UTC, rmottola commented on GWorkspace/TShelf/TShelfFileIcon.m
> +      namelabel = [NSTextField new];
Pasteboard items are nameless, as for now. But I think it could make sense to be able to name them somehow in the future, so I did not remove this.

2021-11-13 22:59 UTC, rmottola commented on GWorkspace/TShelf/TShelfFileIcon.m
> +- (void)draggedImage:(NSImage *)anImage
You are right, strange code here, probably some leftover

2021-11-13 23:47 UTC, rmottola commented on GWorkspace/TShelf/TShelfIconsView.m
>  - (NSComparisonResult)pbiconCompare:(id)other
Relic of when the icon classes where of different nature. Now we can rely on the superclass - I didn't catch this, cleaned it up. Excellent.

2021-11-13 23:48 UTC, rmottola commented on GWorkspace/TShelf/TShelfFileIcon.m
> +  if ([pb setPropertyList: paths forType: NSFilenamesPboardType] == NO)
You are right, strange code here, probably some leftover

2021-11-13 23:50 UTC, rmottola commented on GWorkspace/TShelf/TShelfFileIcon.m
> +- (void)draggedImage:(NSImage *)anImage
cleaned up.

2021-11-14 00:01 UTC, rmottola commented on GWorkspace/TShelf/TShelfPBIcon.m
>  - (void)drawRect:(NSRect)rect
Why? If I remove it, a lot can be cleaned up, but drag operation doesn't start anymore. So it cannot just be removed, but perhaps implemented differently?

2021-11-14 10:04 UTC, fredkiefer commented on GWorkspace/TShelf/TShelfIconsView.m
>  - (NSComparisonResult)iconCompare:(id)other
Why is this method here and not inside TShelfIcon.m?

2021-11-14 10:20 UTC, fredkiefer commented on GWorkspace/TShelf/TShelfPBIcon.m
>  - (void)drawRect:(NSRect)rect
Are we talking about the same method? I was referring to -drawRect:, which just calls super. This should be completely unrelated to drag operations and as it just calls super removing it should in no way change anything.

2021-11-14 10:24 UTC, fredkiefer commented on GWorkspace/TShelf/TShelfFileIcon.m
> +	ASSIGN (icon, [fsnodeRep iconOfSize: ICON_SIZE forNode: node]);
For GNUstep we do, but it is up to you whether you follow it.

2021-11-14 10:35 UTC, fredkiefer commented on GWorkspace/TShelf/TShelfFileIcon.m
> +	      [[self window] postEvent: nextEvent atStart: NO];
You could post the event at the start of the queue by setting atStart to YES.

2021-11-14 10:39 UTC, fredkiefer commented on GWorkspace/TShelf/TShelfFileIcon.m
> +      namelabel = [NSTextField new];
Just be aware that the variable will be nil in all methods for the PB icon.

2021-11-14 20:02 UTC, rmottola commented on GWorkspace/TShelf/TShelfFileIcon.m
> +	ASSIGN (icon, [fsnodeRep iconOfSize: ICON_SIZE forNode: node]);
I will, GWorkspace is part of GNUstep.

2021-11-14 20:14 UTC, rmottola commented on GWorkspace/TShelf/TShelfPBIcon.m
>  - (void)drawRect:(NSRect)rect
Oh, you referred to drawRect... I read the comment referred to the startExternalDragOnEvent call. Sorry, yes you are right. I'll remove it

2021-11-14 20:28 UTC, rmottola commented on GWorkspace/TShelf/TShelfIconsView.m
>  - (NSComparisonResult)iconCompare:(id)other
Oh who knows, we should ask Enrico! But well, now with the superclass the category has no sense, it can just be moved up into it. Did so.

2021-11-14 22:01 UTC, fredkiefer commented on GWorkspace/TShelf/TShelfFileIcon.m
> +  if (node == nil)
Why isn't this check the first statement in this method?

2021-11-15 20:11 UTC, fredkiefer approved these changes
Looks good now.

2021-11-16 18:02 UTC, merged